# Generated by Django 3.2.3 on 2021-10-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_list_processor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='pulication_language',
            new_name='publication_language',
        ),
    ]
